config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: {
    registrations: 'clients/registrations',
    sessions: 'clients/sessions',
    passwords: 'clients/passwords'
  }

  namespace :client do
    resources :profiles, except: [:destroy]
    resources :projects
    resources :donations, only: [:index, :show, :new, :create]
  end

  resources :projects, only: [:index, :show]
  resources :clients, only: [:index]
  post :get_payment_status, to: 'get_payment_status#index', controller: 'get_payment_status'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :cpf_number, presence: true, uniqueness: true
  
  has_many :projects
  has_many :donations
  has_one :profile

  before_save :cpf_valid?

  def cpf_valid?
    unless CPF.valid?(cpf_number)
      errors.add(:base, 'O número do CPF está incorreto.')
      raise ActiveRecord::Rollback
      return
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :client
  belongs_to :category
  has_many :donations, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates :title, presence: true, length: { maximum: 64 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 10, less_than_or_equal_to: 500 }
  validates :description, presence: true, length: { maximum: 512 }
  validates :end_time, presence: true
  validates :start_time, presence: true

  before_save :time_invalid

  def time_invalid
    if start_time > end_time
      errors.add(:base, 'A data final deve ser maior que data inicial.')
      raise ActiveRecord::Rollback
    end

    if (end_time - start_time).days <= 30
      errors.add(:base, 'A diferença entre as datas não deve ser maior que 30 dias.')
      raise ActiveRecord::Rollback
    end

    if end_time <= Time.current
      errors.add(:base, 'A data de encerramento devem ser maiores que o momento atual.')
      raise ActiveRecord::Rollback
    end
  end

  def donation_total_value
    self.donations.where(status: 'paid').to_a.sum { |donation| donation.price_paid }
  end

  def unavailable
    return true if start_time >= Time.current || end_time <= Time.current
    false
  end
end

app/controllers/client/donations_controller.rb
class Client::DonationsController < ClientsController  
  include DonationHelper
  before_action :set_project, only: [:new]
  
  def index
    @donations = Donation.where(client_id: current_client.id).order('created_at DESC')
    @pagy, @donations = pagy(@donations, page: params[:page], items: 6)
  end

  def new
    @donation = Donation.new
  end

  def create
    project_id = params[:paymnet_info][:project_id].to_i

    if info_error(params[:paymnet_info]).present?
      return redirect_to new_client_donation_path(project_id: project_id), alert: "#{info_error(params[:paymnet_info])}"
    end

    @donation = Donation.new(
      client_id: current_client.id,
      project_id: params[:paymnet_info][:project_id].to_i,
      comment: params[:paymnet_info][:comment],
      price_paid: params[:paymnet_info][:price].to_f,
      status: 'pending'
    )

    if @donation.save
      Pagarme::CreateTransactionService.new(
        paymnet_info: params[:paymnet_info],
        donation: @donation
      ).call
    
      if @donation.status == 'error_in_transaction'
        redirect_to new_client_donation_path(project_id: project_id), alert: 'Houve um erro e seu pedido não foi concluído!!!'
      else
        redirect_to project_path(@donation.project), notice: 'Doação realizada com sucesso.'
      end
    else
      redirect_to new_client_donation_path(project_id: project_id), alert: 'Houve um problema para salvar a sua doação'
    end
  end

  private

  def set_project
    begin
      @project = Project.find(params[:project_id].to_i)
    rescue
      redirect_to root_path, notice: 'Não existe um projeto para essa doação.'
    end
  end
end

app/controllers/client/get_payment_status_controller.rb
class Client::GetPaymentStatusController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    return nil if params.blank?
    @donation = Order.find_by(transaction_id: params[:id])
    return nil if @donation.blank?
    return nil if [params[:current_status],'error_in_transaction' ].include? @donation.status
    if @donation.status == 'authorized'
      Pagarme::CaptureTransactionService.new(
        donation: @donation
      ).call
    else
      @donation.update(status: params[:current_status])
    end
  end

end

app/controllers/client/profiles_controller.rb
class Client::ProfilesController < ClientsController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  
  # GET /profile/1
  # GET /profile/1.json
  def show
  end
  
  # GET /profile/new
  def new
    @profile = Client.find(current_client.id).profile
    return redirect_to edit_client_profile_path(@profile)  if @profile.present? 
    @profile = Profile.new
  end
  
  # GET /profile/1/edit
  def edit
  end
  
  # POST /profile
  # POST /profile.json
  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      begin
        response_bank = Pagarme::CreateBankAccountService.new(profile: @profile).call
      rescue
        return redirect_to new_client_profile_path, notice: 'Houve um problema para salvar o perfil.'
      end
      if response_bank.id.present?
        @profile.update(bank_id: response_bank.id)
        response_recipient = Pagarme::CreateRecipientService.new(profile: @profile).call
        if response_recipient.id.present?
          @profile.update(recipient_id: response_recipient.id)
          return redirect_to edit_client_profile_path(@profile), notice: 'Perfil salvo com sucesso.'
        end
      end
      redirect_to new_client_profile_path, notice: 'Houve um problema para salvar o perfil.'      
    else
      redirect_to new_client_profile_path, notice: 'Houve um problema para salvar o perfil.'
    end
  end
  
  # PATCH/PUT /profile/1
  # PATCH/PUT /profile/1.json
  def update
    if @profile.update_attributes(profile_params)
      begin
        response_bank = Pagarme::CreateBankAccountService.new(profile: @profile).call
      rescue
        return redirect_to new_client_profile_path, notice: 'Houve um problema para salvar o perfil.'
      end
      if response_bank.id.present?
        @profile.reload.update(bank_id: response_bank.id)
        if @profile.recipient_id.blank?
          response_recipient = Pagarme::CreateRecipientService.new(profile: @profile).call
        else
          response_recipient = Pagarme::UpdateRecipientService.new(profile: @profile).call
        end
        if response_recipient.id.present?
          @profile.reload.update(recipient_id: response_recipient.id)
          return redirect_to edit_client_profile_path(@profile), notice: 'Perfil atualizado com sucesso.'
        end
      end
      redirect_to edit_client_profile_path(@profile), notice: 'Houve um problema para salvar o perfil.'
    else
      redirect_to edit_client_profile_path(@profile), notice: 'Houve um problema para salvar o perfil.'
    end
  end
  
  private

    def set_profile
      @profile = Profile.find(params[:id])
      authorized_profile
    end

    def authorized_profile
      if current_client.id != @profile.client.id
        redirect_to new_client_profile_path, alert: 'Você não está autorizado a editar esse Perfil.'
      end
    end

    def profile_params
      params.require(:profile).permit( :state, :city, :neighborhood, :street, :street_number, :zipcode,
      :bank_code, :agency, :account, :agency_dv, :account_dv, :account_type,
      :legal_name, :document_number).merge(client_id: current_client.id)
    end
end

app/controllers/client/projects_controller.rb
class Client::ProjectsController < ClientsController
  include EnabledClient
  before_action :set_project, only: [:edit, :update, :show, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @q = Project.search(params[:q])
    @projects = @q.result.where(:client_id => current_client.id)
    @pagy, @projects = pagy(@projects, page: params[:page], items: 8)
  end
  
  # GET /projects/new
  def new
    return redirect_to new_client_profile_path, alert: 'Atualize seu Perfil.' unless profile_is_complete?(current_client)
    @project = current_client.projects.build
  end
  
  def show
    redirect_to edit_client_project_path(@project)
  end

  # GET /projects/1/edit
  def edit
  end
  
  # POST /projects
  # POST /projects.json
  def create
    @project = current_client.projects.build(project_params)
    if @project.save
      redirect_to edit_client_project_path(@project), notice: 'Projeto criado com sucesso.'
    else
      render :new
    end
  end
  
  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to edit_client_project_path(@project), notice: 'Projeto atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to client_projects_path, notice: 'Seu projeto foi excluído.'
  end
  
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.friendly.find(params[:id])
    authorized_project
  end

  def authorized_project
    if current_client.id != @project.client.id
      redirect_to client_projects_path, alert: 'Você não está autorizado a editar esse projeto.'
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params 
    params.require(:project).permit(:category_id, :title, :price, :description,
      :image, :end_time, :start_time).merge(client_id: current_client.id)
  end
end

app/controllers/clients/confirmations_controller.rb
# frozen_string_literal: true

class Clients::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/clients/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Clients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/clients/passwords_controller.rb
# frozen_string_literal: true

class Clients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/clients/registrations_controller.rb
# frozen_string_literal: true

class Clients::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:cpf_number, :name, :surname, :email, :password])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:cpf_number, :name, :surname, :email, :password])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/clients/sessions_controller.rb
# frozen_string_literal: true

class Clients::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/clients/unlocks_controller.rb
# frozen_string_literal: true

class Clients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_client!, except: [:index]

  def index
    redirect_to new_client_session_path
  end
end
  

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]

  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result.includes(:client, :category)
                         .where('start_time <= ?', Time.current)
    @pagy, @projects = pagy(@projects, page: params[:page], items: 20)
  end

  def show
    @donations = Donation.where(project_id: @project.id, status: 'paid')
  end
  
  private

  def set_project
    @project = Project.friendly.find(params[:id])
  end
end

app/views/client/projects/_form.html.erb
<div class="columns">
  <div class="column is-10 is-offset-1 is-centered">

    <%= form_for [:client, @project ]  do |f| %>
      <% if @project.errors.any? %>
        <div id="error_explanation">
          <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li class="is-danger" style="color:red"><%= message %></li>
          <% end %>
          </ul>
        </div><br>
      <% end %>

        <div class="columns">
          <div class="field column is-7">
            <div class="control">
              <label>Título</label>
              <%= f.text_field :title, :required => true, class: 'input' %>
            </div>
          </div>
          <div class="field column is-2">
            <div class="control">
              <label>Preço de Arrecadação</label>
              <%= f.number_field :price, :required => true, type:"number", step: 0.01, class: 'input' %>
            </div>
          </div>

          <div class="field column is-3">
            <div class="control">
              <label>Categoria</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%=  f.collection_select(:category_id, Category.all, :id, :title, { :prompt => 'Categoria', :selected => @project.category_id }, { class: 'form-control' }) %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <label>Descrição</label>
            <%= f.text_area :description, :required => true, class: 'textarea' %>
          </div>
        </div>

        <div class="columns">
          <div class="column is-3"><br>
            <div class="file is-fullwidth is-link has-name">
              <label class="file-label">
                <%= f.file_field :image, class: "file-input", data: { allowed_file_extensions: 'png jpeg jpg jfif' } %>
                <span class="file-cta">
                  <span class="file-icon">
                    <i class="fa fa-upload"></i>
                  </span>
                  <span class="file-label">
                    Imagem
                  </span>
                </span>
                <span class="file-name">
                  <%= "arquivo salvo" if @project.image.present? %>
                </span>
              </label>
            </div>
            <p class="help">Aceitamos apenas arquivos em: *jpj *pnj *jpeg *jfif. A Imagem devem ser quadrada e possuir tamanho máximo de 4mb.</p>
          </div>

          <div class="field column is-3">
            <div class="control">
              <label>Data de Início</label> 
              <%= f.datetime_local_field :start_time, :required => true, class: 'input' %>
            </div>
          </div>

          <div class="field column is-3">
            <div class="control">
              <label>Data de Encerramento</label> 
              <%= f.datetime_local_field :end_time, :required => true, class: 'input' %>
            </div>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%=  f.submit "Salvar", class: 'button is-primary is-outlined is-fullwidth is-uppercase' %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/client/projects/edit.html.erb
<%= render 'form', project: @project, :formats => [:html] %>

app/views/client/projects/index.html.erb
<section class="columns is-fullheight">
<div class="column is-2 is-narrow-mobile is-fullheight">
  <%=  search_form_for @q , url: client_projects_path, method: :get do |f|%>
    <aside class="menu">
      <p class="menu-label">
        Filtros
      </p>
      <ul class="menu-list is-3">
        <%= sort_link(@q, :title, default_order: :asc) %>
        <%= sort_link(@q, :end_time, default_order: :asc) %>
        <%= sort_link(@q, :price, default_order: :asc) %>
      </ul>
    </aside>
</div>
<div class="column is-10 is-offset-1">
  <div class="columns">
    <div class="column is-7">
      <div class="columns is-mobile">
        <div class="column">
          <div class="control">
            <%= f.search_field :title_cont, class: 'input is-rounded', placeholder: 'Pesquisar por título' %>
          </div>
        </div> 
        <div class="column is-3">
          <%= button_tag class: "button is-rounded" do %>
            <i class="fa fa-search"></i>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
    <div class="column">
      <%= link_to "Criar Projeto", new_client_project_path, class: 'button is-info is-outlined is-uppercase' %>
    </div>
  </div>
  <div class="columns is-multiline is-centered">
    <div class="column is-10"><br>
      <% if @projects.blank? %>
        <p>Cadastre um Projeto :)</p>
      <% else %>
        <% @projects.each do |project| %>
          <div class="columns" style="padding: 0px;margin-bottom: 0px;">   
            <div class="column box is-5">
              <p class="f4"><%=  project.title %></p>
              <p>Data de Encerramento: <%= project.end_time.strftime("%d/%m/%Y") %></p>
              <p>Meta: <%= number_to_currency(project.price) %></p>
              <p>Arrecadado: <%= number_to_currency(project.donation_total_value) %></p>
              <%= link_to "Editar", edit_client_project_path(project), class: 'button is-info is-outlined is-small is-uppercase' %>
              <%= link_to "Excluir", client_project_path(project), method: :delete, data: {confirm:"Você tem certeza que deseja excluir?"}, class: 'button is-danger is-outlined is-small is-uppercase' %>
            </div>
            <hr class="hr-color" style="padding: 0px; margin-top: 0px;" />
          </div>
        <% end %>
        <div class="column is-5">
          <%= pagy_bulma_nav(@pagy).html_safe %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</section>

app/views/client/projects/new.html.erb
<%= render 'form', project: @project %>