config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: {
    registrations: 'clients/registrations',
    sessions: 'clients/sessions',
    passwords: 'clients/passwords'
  }

  namespace :client do
    resources :profiles, except: [:destroy]
    resources :projects
    resources :donations, only: [:index, :show, :new, :create]
  end

  resources :projects, only: [:index, :show]
  resources :clients, only: [:index]
  post :get_payment_status, to: 'get_payment_status#index', controller: 'get_payment_status'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :client
  belongs_to :category
  has_many :donations, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates :title, presence: true, length: { maximum: 64 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 10, less_than_or_equal_to: 500 }
  validates :description, presence: true, length: { maximum: 512 }
  validates :end_time, presence: true
  validates :start_time, presence: true

  before_save :time_invalid

  def time_invalid
    if start_time > end_time
      errors.add(:base, 'A data final deve ser maior que data inicial.')
      raise ActiveRecord::Rollback
    end

    if (end_time - start_time).days <= 30
      errors.add(:base, 'A diferença entre as datas não deve ser maior que 30 dias.')
      raise ActiveRecord::Rollback
    end

    if end_time <= Time.current
      errors.add(:base, 'A data de encerramento devem ser maiores que o momento atual.')
      raise ActiveRecord::Rollback
    end
  end

  def donation_total_value
    self.donations.where(status: 'paid').to_a.sum { |donation| donation.price_paid }
  end

  def unavailable
    return true if start_time >= Time.current || end_time <= Time.current
    false
  end
end

app/controllers/client/projects_controller.rb
class Client::ProjectsController < ClientsController
  include EnabledClient
  before_action :set_project, only: [:edit, :update, :show, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @q = Project.search(params[:q])
    @projects = @q.result.where(:client_id => current_client.id)
    @pagy, @projects = pagy(@projects, page: params[:page], items: 8)
  end
  
  # GET /projects/new
  def new
    return redirect_to new_client_profile_path, alert: 'Atualize seu Perfil.' unless profile_is_complete?(current_client)
    @project = current_client.projects.build
  end
  
  def show
    redirect_to edit_client_project_path(@project)
  end

  # GET /projects/1/edit
  def edit
  end
  
  # POST /projects
  # POST /projects.json
  def create
    @project = current_client.projects.build(project_params)
    if @project.save
      redirect_to edit_client_project_path(@project), notice: 'Projeto criado com sucesso.'
    else
      render :new
    end
  end
  
  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to edit_client_project_path(@project), notice: 'Projeto atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to client_projects_path, notice: 'Seu projeto foi excluído.'
  end
  
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.friendly.find(params[:id])
    authorized_project
  end

  def authorized_project
    if current_client.id != @project.client.id
      redirect_to client_projects_path, alert: 'Você não está autorizado a editar esse projeto.'
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params 
    params.require(:project).permit(:category_id, :title, :price, :description,
      :image, :end_time, :start_time).merge(client_id: current_client.id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]

  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result.includes(:client, :category)
                         .where('start_time <= ?', Time.current)
    @pagy, @projects = pagy(@projects, page: params[:page], items: 20)
  end

  def show
    @donations = Donation.where(project_id: @project.id, status: 'paid')
  end
  
  private

  def set_project
    @project = Project.friendly.find(params[:id])
  end
end

app/views/projects/index.html+mobile.erb
<%= search_form_for @q , url: projects_path do |f| %>
  <div class="columns ">
    <div class="column is-8">
      <div class="control">
        <%= f.search_field :title_or_category_title_cont, class:'input', placeholder: 'Pesquisar produtos' %>
      </div>
    </div>
  </div>
  <section class="columns is-fullheight">
    <div class="column is-2 is-narrow-mobile is-fullheight">
    <div class="tags are-medium">
      <span class="tag is-info is-light filter-mobile-button">+ Filtros <sup class="pad-cart_count"><i class="fa fa-sort-desc" aria-hidden="true"></i></sup></span>
      <span class="tag is-info is-light categories-mobile-button">Categorias  <sup class="pad-cart_count"><i class="fa fa-sort-desc" aria-hidden="true"></i></sup></span>
      <%=  f.submit "Filtrar", class: 'button is-danger is-outlined is-uppercase is-small' %>
    </div>
      <div class="filter-mobile">
        <ul class="menu-list is-3">
          <li>Preço Arrecadação Mínimo</li>
            <%= f.number_field :price_gteq, class: 'input', min: 1 %>
          <li>Preço Arrecadação Máximo</li>
            <%= f.number_field :price_lteq, class: 'input', min: 1 %>
        </ul>
        <p class="menu-label">
          Ordenar
        </p>
        <ul class="menu-list is-3">
          <%= sort_link(@q, :title, default_order: :asc) %>
          <%= sort_link(@q, :end_time, default_order: :asc) %>
          <%= sort_link(@q, :price, default_order: :asc) %>
        </ul>  
      </div>
      <div class="categories-mobile">
        <% Category.all.each do |category| %>
          <% if category.project_present?%>
            <ul class="menu-list">
              <%= link_to category.title, projects_path(@projects, q: {category_title_eq: category.title })%>
            </ul>
            <hr class="hr-category hr-color">
          <% end %>
        <% end %>
      </div>
  </div>
<% end %>

<div class="column is-9">
  <% @projects.each do |project| %>
    <div class="columns is-mobile is-vcentered" style="padding: 0px;margin-bottom: 0px;">
      <div class="column is-two-fifths ">
        <%= link_to project_path(project) do %> 
          <%= image_tag project.image_url(:default), class: 'project-image-mobile' %>
        <% end %>
      </div>
      <%= link_to project_path(project) do %>
        <div class="column">
          <h3 class="f5"><%= truncate(project.title, length: 35) %></h3>
           <p class="has-text-gray fg pt1">Meta: <%= number_to_currency(project.price) %></p>
            <p class="has-text-gray fg pt1">Arrecadado: <%= number_to_currency(project.donation_total_value) %></p>       
          <% if project.unavailable %>
            <span class="tag is-danger">indisponível</span><br>
          <% end %>
        </div>
      <% end %>
    </div>
    <hr class="hr-color" style="padding: 0px; margin-top: 0px;" />
  <% end %>
</div>
<%= pagy_bulma_nav(@pagy).html_safe if @projects.present? %>
</section>

app/views/projects/index.html.erb
<%= search_form_for @q , url: projects_path do |f| %>
<section class="columns is-fullheight">
  <div class="column is-2 is-narrow-mobile is-fullheight">
    <aside class="menu">
      <p class="menu-label">
        Mais Filtros
      </p>
      <ul class="menu-list is-3">
        <li>Preço Arrecadação Mínimo</li>
          <%= f.number_field :price_gteq, class: 'input', min: 1 %>
        <li>Preço Arrecadação Máximo</li>
          <%= f.number_field :price_lteq, class: 'input', min: 1 %>
      </ul>
      <p class="menu-label">
        Ordenar
      </p>
      <ul class="menu-list is-3">
        <%= sort_link(@q, :title, default_order: :asc) %>
        <%= sort_link(@q, :end_time, default_order: :asc) %>
        <%= sort_link(@q, :price, default_order: :asc) %>
      </ul>  
      <p class="menu-label">
        Categorias
      </p>
      <% Category.all.each do |category| %>
        <% if category.project_present?%>
          <ul class="menu-list">
            <%= link_to category.title, projects_path(@projects, q: {category_title_eq: category.title })%>
          </ul>
          <hr class="hr-category hr-color">
        <% end %>
      <% end %>
    </aside>
  </div>
<div class="column is-10"> 
  <div class="columns">
    <div class="column is-4">
      <%= f.search_field :title_or_category_title_cont, class:'input', placeholder: 'Pesquisar' %>
    </div>
    <div class="column is-1">
      <%=  f.submit "Filtrar", class: 'button is-danger is-outlined is-uppercase' %>
    </div>
  </div>
<% end %>
<br>
  <div class="project-index-grid">
    <% @projects.each do |project| %>
      <div class="project box" style="margin-bottom: 0rem;">
        <div class="project-thumb">
          <%= link_to image_tag(project.image_url(:default)), project_path(project) %>
        </div>
        <%= link_to project_path(project) do%>
          <div class="pa2">
            <h3 class="subtitle f5" style = "margin-bottom: 0px"><%= truncate(project.title, length: 35)%></h3>
            <p class="has-text-gray fg pt1">Meta: <%= number_to_currency(project.price) %></p>
            <p class="has-text-gray fg pt1">Arrecadado: <%= number_to_currency(project.donation_total_value) %>  </p>       
            <% if project.unavailable %>
              <span class="tag is-danger">indisponível</span><br>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <br><%= pagy_bulma_nav(@pagy).html_safe if @projects.present? %>
</div>
</section>

app/views/projects/show.html.erb
<section class="section container project-show">
  <div class="columns">
    <div class="column is-6">
      <div class="pad-slideshow">
        <div class="columns">
           <%= image_tag @project.image_url(:default), class: 'project-image' %>
          <br>
        </div>
      </div>
    </div>
    <div class="column is-6">
      <div class="box pa4">
        <h1 class="subtitle is-5 has-text-left" style="margin-bottom: 0px;"><%= @project.title %></h4><br>
        <p class="has-text-left">
          Meta de Arrecadação: <%= number_to_currency(@project.price) %> <br> 
          Total Arrecado: <%= number_to_currency(@project.donation_total_value) %> <br>
          Data de encerramento: <%= @project.end_time.strftime("%d/%m/%Y, %H:%M h") %>
        </p>
        <br><br>
        <% if @project.unavailable %>
          <%= link_to 'Indisponível', projects_path , class: 'button is-danger is-uppercase is-outlined add-to-order' %>
        <% else %>
          <%= link_to 'Apoiar', new_client_donation_path(project_id: @project.id), class: 'button is-info is-uppercase is-outlined add-to-order' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="column is-6">
    <div class="content pa3 bg-white border-radius-3">
      <h2 class="subtitle is-4">Descrição</h4>
      <p stytle="text-align: justify;"><%= @project.description.gsub(/\n/, '<br/>').html_safe  %></p>
      <h3 class="subtitle is-5">Apoiadores</h4>
      <% if @donations.present? %>
        <% @donations.each do |donation|%>
          <article class="media">
            <div class="media-content">
              <div class="content">
                <p>
                  <strong><%= donation.client.name %> <%= donation.client.surname %></strong>
                  <br>
                  <%= donation.comment %>
                </p>
              </div>
            </div>
          </article>
        <% end %>
      <% else %>
        <p>Seja o primeiro :)</p>
      <% end %>
    </div>
  </div>
</section>