config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: {
    registrations: 'clients/registrations',
    sessions: 'clients/sessions',
    passwords: 'clients/passwords'
  }

  namespace :client do
    resources :profiles, except: [:destroy]
    resources :projects
    resources :donations, only: [:index, :show, :new, :create]
  end

  resources :projects, only: [:index, :show]
  resources :clients, only: [:index]
  post :get_payment_status, to: 'get_payment_status#index', controller: 'get_payment_status'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to root_path, class:"navbar-item is-hidden-mobile is-hidden-tablet-only" do %>
        <%= image_tag 'logo.png'%>
      <% end  %>

      <div class="navbar-item is-hidden-desktop is-hidden-widescreen" data-target="navbar">
        <%= link_to projects_path, class:"navbar-item"  do %>
          <span class="icon is-small">
            <i class="fa fa-search fa-lg"></i>
          </span>
        <% end %>
      </div>

      <%= link_to root_path, class:"navbar-item nav-center is-hidden-desktop is-hidden-widescreen", style: "flex: 1; justify-content: center;" do %>
        <%= image_tag 'logo.png' %>
      <% end  %>
      
      <span class="navbar-burger burger">
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>
    <div id="navbar" class="navbar-menu">
      <div class="navbar-end">
        <%= link_to 'Home', root_path, class: 'navbar-item is-size-6' %>
        <%= link_to 'Apoie', projects_path, class: 'navbar-item is-size-6' %> 
        <% if client_signed_in? %>
          <%= link_to 'Doações', client_donations_path, class: 'navbar-item' %>
          <%= link_to 'Projetos', client_projects_path, class: 'navbar-item' %>
          <div class="navbar-item has-dropdown is-hoverable">
            <%= link_to 'Mais', new_client_profile_path, class: 'navbar-link' %>
            <div class="navbar-dropdown is-right">
                <%= link_to 'Conta', new_client_profile_path, class: 'navbar-item' %>
                <%= link_to current_client.name, edit_client_registration_path, class: 'navbar-item' %>
                <%= link_to 'Sair', destroy_client_session_path, method: :delete, class: 'navbar-item' %>
            </div>
          </div>
        <% else %>
          <%= link_to 'Logar/Cadastrar', new_client_session_path, class: 'navbar-item is-size-6' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<style>
  nav.navbar {
    height: 6rem;
    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06) !important;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="description" content="crowdfunding">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-widthm initial-scale=1">
    <meta name="author" content="Crowdfunding">
    <meta http-equiv="Content-Language" content="pt-br">
    <meta name="theme-color" content="#e63c35"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <%= render partial: 'layouts/navbar' %>    
    <section class="section">
      <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="notification is-danger global-notification">
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>
      <%= yield %>
    </section>
  </body>
</html>